# Dockerfile para Desenvolvimento do Frontend Next.js
FROM node:18-alpine

WORKDIR /app

# Instalar dependências
COPY package.json ./
RUN npm install --legacy-peer-deps

# Copiar código fonte
COPY . .

EXPOSE 3000

ENV NODE_ENV development
ENV PORT 3000

CMD ["npm", "run", "dev"] 